language: cpp

# reduce clone time by only getting the latest commit and not the whole history (default for travis is 100)
git:
  depth: 1

# only run travis on the master branch
branches:
  only:
    - master

# define complier for build
compiler:
  - clang
  #gcc

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libbz2-dev libncurses5-dev libmysqlclient-dev libreadline-dev libsdl1.2-dev libssl-dev zlib1g-dev

install:
 - mkdir bins
 - cd bin
 - cmake ../
 
script:
  - cd ..
  - cd bin
  - make -j 10
