sudo: false
language: cpp

os:
  - linux

compiler:
  - gcc

git:
  depth: 1

env:
  global:
    - secure: "Zk3bAxnp4OHPMMZYOSoM2chuMZXomp7BFcT54/Ag6C8RCqtpqQ+E6yHRp861xdWSVo9uZ/uGmD1pwPiIUK8Vs80+OwhFVvtor2MGXyQKX1oFYBg0mo5Z3Xzy+OPa3e0YBbe6SSqdUzDE1hIa7OrU8GWciIMobWQS7XIBbWg3TFU="

before_install:
  - if [ "$COMPILER" = "g++-6" ]; then export CXX="g++-6" CC="gcc-6"; fi

install:
  - mkdir ascemu_build
  - cd ascemu_build
  - cmake ../ -DCMAKE_BUILD_TYPE=Release -DBUILD_TOOLS=1 -DASCEMU_VERSION=WotLK

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - cmake
    - zlib1g-dev
    - libssl-dev
    - libpcre3-dev
    - libbz2-dev
    - libmysqlclient-dev
    - libmysql++-dev
    - gcc-6
    - g++-6
  coverity_scan:
    project:
      name: AscEmu/AscEmu
      description: MMORPG Framework
    notification_email: autokaori@gmail.com
    build_command_prepend: cmake ../ -DCMAKE_BUILD_TYPE=Release -DBUILD_TOOLS=0 && cov-configure --comptype gcc --compiler gcc-5 --template
    build_command: make -j2
    branch_pattern: coverity_scan

before_script:
  - ${CXX} --version
  - ${CC} --version
  - cmake --version

script:
  - make -j2

#after_script:
#  - cat /home/travis/build/AscEmu/AscEmu/ascemu_build/cov-int/build-log.txt
#  - echo "===================================================================================================="
#  - cat /home/travis/build/AscEmu/AscEmu/ascemu_build/cov-int/scm_log.txt