language: cpp

# reduce clone time by only getting the latest commit and not the whole history (default for travis is 100)
git:
  depth: 1

# only run travis on the master branch
branches:
  only:
    - master
    - coverity_scan

# define complier for build
compiler:
  - gcc

before_install:
 - echo "yes" | sudo add-apt-repository ppa:kalakris/cmake
 - echo "yes" | sudo add-apt-repository ppa:ubuntu-toolchain-r/test
 - sudo apt-get -qq update
 - sudo apt-get -qq install build-essential libtool gcc-4.8 g++-4.8 make cmake
 - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
 - sudo apt-get install -qq libbz2-dev libncurses5-dev libmysqlclient-dev libreadline-dev libsdl1.2-dev libssl-dev zlib1g-dev

install:
 - mkdir bin
 - cd bin
 - cmake ../

script:
 - cd ..
 - cd bin
 - make -j 10

 env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "Zk3bAxnp4OHPMMZYOSoM2chuMZXomp7BFcT54/Ag6C8RCqtpqQ+E6yHRp861xdWSVo9uZ/uGmD1pwPiIUK8Vs80+OwhFVvtor2MGXyQKX1oFYBg0mo5Z3Xzy+OPa3e0YBbe6SSqdUzDE1hIa7OrU8GWciIMobWQS7XIBbWg3TFU="

addons:
  coverity_scan:
    project:
      name: "AscEmu/AscEmu"
      description: "3.3.5 World of Warcraft game server"
    notification_email: autokaori@gmail.com
    build_command_prepend: "make clean"
    build_command:   "make -j 10"
    branch_pattern: coverity_scan
